spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 197334622192-2ohlkmq4gl71m3v4qttq3ub1erktco6j.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email

          naver:
            client-id: 9XYnNT__GZ_8Dd_rvUEI
            client-secret: 50usbXvvPp
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

    mvc:
      static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/news_data?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul # ??? db connection url
    username: root       #  db username
    password: 0008 #  db password

  jpa:
    hibernate:
      ddl-auto: update # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # ??? ?? ?? SQL ? ?? ?? ???
        show_sql: true # jpa ? hibernate ? ?? CRUD ? ?? ?? ?? CRUD ? SQL ? ???? ?? ??.
        use_sql_comments: true

#logging.level:
#  org.hibernate.SQL: debug



#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:news_data # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
#    username: sa # username과 password는 자신의 설정에 맞게
#    password:
#    driver-class-name: org.h2.Driver


chrome:
  driverPath: /Users/yeopking/Programing/spring_study/collecting_data_news/chromedriver-mac-arm64_version_121/chromedriver
  naverUrl: https://search.naver.com/search.naver?ssc=tab.news.all&where=news&sm=tab_jum&query=
  daumUrl: https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q=
  googleUrl: https://news.google.com/search?q=